services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP Bolt
      - "7687:7687"  # Bolt
    volumes:
      - ./data:/data  # Mounting data directory for persistence
    environment:
      NEO4J_AUTH: neo4j/password  # Set initial username and password
      NEO4JLABS_PLUGINS: '["apoc"]'
    
  